### ISSUE TITLE
Hey, same name repo :)

### ISSUE THREAD

**Issue by keithwhor** [nodal/nodal#1]
Hey there,

I'm the lead contributor on [Nodal](http://github.com/keithwhor/nodal) and was wondering if there was any way you'd consider a transfer of ownership of the organization name? If not --- totally understand. The code we write is like our baby. :) Hope I'm not out of line!

Cheers, and best of luck with the project.

**Comment by fbbdev** [comment]
I replied by e-mail. Tell me if you don't get the message.
