### ISSUE TITLE
Activity and pull requests ?

### ISSUE THREAD

**Issue by nyue** [nodal/nodal#2]
Hi,

  Is this still actively being worked on and accepting pull requests etc ?

Cheers

**Comment by fbbdev** [comment]
Hi,

Thank you for your interest.

As you can see from open issues, some important features are still missing.
I'd like to complete the project but I never found the time in the past and
it will be even harder in the coming years, so development is substantially
stalled.

However, I still review new issues and pull requests and I will accept code
if I am satisfied with its quality and it adheres to the project's code
style. I will even try to improve PRs before pulling if I can find the time
to.

Best wishes,

Fabio

Il Sab 5 Dic 2020, 04:05 Nicholas Yue <notifications@github.com> ha scritto:

**Comment by fbbdev** [comment]
Hi,

please excuse me and ignore my previous response, it's very late here and I got confused with another project of mine.

I'm not maintaining this project anymore, I think some ideas were maybe good but in the end I didn't really need it, moreover I feel C++ is a bit too rigid for this use case.

I see it's getting a lot of attention lately, not sure why. In any case I think the state of the code is not bad and I want to leave the repository open here for personal reasons.

That said, I will respond to issues and accept PRs if I deem their quality and code style appropriate.

Cheers,

Fabio
